#!/bin/sh
# --------------------------------------
# Goal:
#   - パーセントエンコードされた文字列をデコードする
#
# Dependencies:
#   - nkf
#
# Usage:
#   decode [ENCODED_STRING]
# --------------------------------------

echo "$1" | tr % = | nkf -mQ
