#!/bin/sh

PROGNAME=$(basename $0)
VERSION="0.1"

function usage() {
cat <<_EOT_
Usage:
  $PROGNAME [-u <base_url>]
  $PROGNAME <url> <url> <url>...

Description:
  Facebook og data bulk scraping

Options:
  -u ARG
  -h

Dependencies:
  - page_list (https://github.com/naokazuterada/dotfiles/blob/master/functions/page_list)

_EOT_
exit 1
}

function need_page_list() {
cat <<_EOT_
[NOTICE] You need to install page_list command if you use 'u' option

It's available here.
https://github.com/naokazuterada/dotfiles/blob/master/functions/page_list

Or don't use 'u' command but just input urls like below.
$PROGNAME <url> <url> <url>...

_EOT_
exit 1
}

while getopts u:h OPT
do
  case $OPT in
    "u" ) url="$OPTARG";;
    "h" ) usage;;
    \?  ) usage;;
  esac
done

if test "${url}" == ""; then
  url_list=("$@")
else
  if [ `which page_list` ]; then
    url_list=(`page_list -u $url -d ' '`)
  else
    need_page_list
  fi
fi

if [ ${#url_list[*]} = 0 ]; then
  echo "[NOTICE] URL is empty."
  usage
fi

for i in `seq 1 ${#url_list[*]}`
do
  curl -d scrape=true -d id=${url_list[$i-1]} https://graph.facebook.com/
done
