# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="arrow"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to disable command auto-correction.
# DISABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git osx terminalapp gem bundler rails)

source $ZSH/oh-my-zsh.sh

# User configuration

autoload -Uz zmv

# cd XXX
alias d='cd ~/Desktop'
alias s='cd ~/Sites'
alias dotfiles='cd ~/.dotfiles'
alias dotfile='dotfiles'
alias dot='dotfiles'

# open XXX
alias od='open ~/Desktop'
alias odot='open ~/Sites'
alias os='open ~/Sites'

alias o='source ~/.dotfiles/functions/open_with_sublime_sourcetree.sh'
alias a='source ~/.dotfiles/functions/open_with_atom_sourcetree.sh'
alias mkcd='source ~/.dotfiles/functions/mkdir_cd.sh'

alias m='middleman'
alias middleman_new='source ~/.dotfiles/functions/middleman_new.sh'
alias m_new='middleman_new'

alias rails_new='source ~/.dotfiles/functions/rails_new.sh'

alias f='foreman'
alias v='vagrant'
alias st='stree' # SourceTree

# rbenvを使った環境用
function re   { rbenv exec $@ }
function reb  { rbenv exec bundle $@ }
function rebe { rbenv exec bundle exec $@ }

alias http='python -m SimpleHTTPServer'

# プロセス名から選んでシグナルを送る
alias psint='ps -ax | peco | xargs kill -2' # 割り込み（Ctrl+Cと同じ）
alias psquit='ps -ax | peco | xargs kill -3' # 終了
alias pskill='ps -ax | peco | xargs kill -9' # 強制終了
alias psterm='ps -ax | peco | xargs kill -15' # 終了

# export PATH="/Users/terada/.rbenv/shims:/Users/terada/.rbenv/shims:/Users/terada/Qt/5.1.0/clang_64/bin:/Applications/SenchaSDKTools-2.0.0-beta3:/Applications/SenchaSDKTools-2.0.0-Beta/jsbuilder:/Applications/SenchaSDKTools-2.0.0-Beta/bin:/Applications/SenchaSDKTools-2.0.0-Beta:/usr/local/git/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/opt/local/lib/postgresql91/bin:/Applications/SenchaSDKTools-2.0.0-Beta:/bin:/Applications/SenchaSDKTools-2.0.0-Beta/bin:/Applications/SenchaSDKTools-2.0.0-Beta/jsbuilder:/Applications/SenchaSDKTools-2.0.0-beta3:/Users/terada/bin:/Users/terada/ratproxy:/usr/local/Cellar/android-sdk/20130219/tools:/usr/local/Cellar/android-sdk/20130219/platform-tools:/Users/terada/bin/repo:/usr/local/share/npm/bin"

export PATH=$PATH:/Applications/SenchaSDKTools-2.0.0-Beta
export PATH=$PATH:/Applications/SenchaSDKTools-2.0.0-Beta/bin
export PATH=$PATH:/Applications/SenchaSDKTools-2.0.0-Beta/jsbuilder
export PATH=$PATH:/Applications/SenchaSDKTools-2.0.0-beta3
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/bin/FDK/Tools/osx
export PATH=$PATH:$HOME/Qt/5.1.0/clang_64/bin
export PATH=$PATH:$HOME/Qt5.1.0/5.1.0/clang_64/bin
export PATH=$PATH:$HOME/.rbenv/bin
export PATH=$PATH:/usr/local/heroku/bin ### Added by the Heroku Toolbelt
export PATH=$PATH:$HOME/.dotfiles/functions

export SENCHA_SDK_TOOLS_2_0_0_BETA3="/Applications/SenchaSDKTools-2.0.0-beta3"
# Initialization for FDK command line tools.Wed Dec  4 19:20:56 2013
export FDK_EXE=$HOME/bin/FDK/Tools/osx

# Comment out by terada because command not found occur on zsh
# Node Completion - Auto-generated, do not touch.
#shopt -s progcomp
#for f in $(command ls ~/.node-completion); do
# f="$HOME/.node-completion/$f"
# test -f "$f" && . "$f"
#done

# for rbenv
if which rbenv > /dev/null; then
  export RBENV_ROOT=$HOME/.rbenv
  export PATH=$PATH:$RBENV_ROOT/shims
  eval "$(rbenv init -)"
fi

#for bundler
export PATH=$PATH:./vendor/bin:./bin

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"
